import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { getRecommendation } from './recommendation.mapper';

const PDFDocument = require('pdfkit');

@Injectable()
export class ReportService {
  constructor(private readonly prisma: PrismaService) {}

  async getReport(auditId: string) {
    const job = await this.prisma.auditJob.findUnique({
      where: { id: auditId },
      include: { result: true },
    });

    if (!job || !job.result) {
      throw new NotFoundException('Audit report not found');
    }

    const issues = (job.result.issues as any[]).map((issue: any) => ({
      ...issue,
      ...getRecommendation(issue.ruleId),
    }));

    return {
      url: job.url,
      auditedAt: job.result.createdAt,
      overallScore: job.result.overallScore,
      categoryScores: job.result.categoryScores,
      issues,
      metadata: job.result.metadata,
    };
  }

  async generatePdf(auditId: string): Promise<Buffer> {
    const report = await this.getReport(auditId);

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc
        .fontSize(24)
        .text('SEO Audit Report', { align: 'center' })
        .moveDown(0.5);

      doc
        .fontSize(12)
        .fillColor('#666')
        .text(`URL: ${report.url}`, { align: 'center' })
        .text(`Date: ${new Date(report.auditedAt).toLocaleDateString()}`, {
          align: 'center',
        })
        .moveDown(1);

      // Overall Score
      doc
        .fontSize(18)
        .fillColor('#000')
        .text(`Overall Score: ${report.overallScore}/100`, { align: 'center' })
        .moveDown(1);

      // Category Scores
      doc
        .fontSize(14)
        .text('Category Breakdown', { underline: true })
        .moveDown(0.5);

      for (const cat of report.categoryScores as any[]) {
        doc
          .fontSize(11)
          .text(
            `${cat.category.toUpperCase()} (${Math.round(cat.weight * 100)}% weight): ${cat.score}/100 — ${cat.issueCount} issue(s)`,
          );
      }
      doc.moveDown(1);

      // Issues
      doc.fontSize(14).text('Issues Found', { underline: true }).moveDown(0.5);

      for (const issue of report.issues) {
        doc
          .fontSize(11)
          .fillColor(this.getSeverityColor(issue.severity))
          .text(`[${issue.severity.toUpperCase()}] ${issue.title}`)
          .fillColor('#000')
          .fontSize(10)
          .text(issue.description)
          .fillColor('#0066cc')
          .text(`Fix: ${issue.fix || issue.recommendation}`)
          .fillColor('#000')
          .moveDown(0.5);
      }

      // Footer
      doc
        .moveDown(2)
        .fontSize(9)
        .fillColor('#999')
        .text('Generated by SEO Analysis Platform', { align: 'center' });

      doc.end();
    });
  }

  private getSeverityColor(severity: string): string {
    switch (severity) {
      case 'critical':
        return '#dc2626';
      case 'high':
        return '#ea580c';
      case 'medium':
        return '#ca8a04';
      case 'low':
        return '#2563eb';
      default:
        return '#6b7280';
    }
  }
}
